theme: jekyll-theme-minimal

title:  CSCI 2200 | Algorithms

email: ltoma@bowdoin.edu

description: >- # this means to ignore newlines until "baseurl:"
 Fall 21, Bowdoin College 

github_username:  lauratoma

plugins:
  - jekyll-feed

