theme: jekyll-theme-cayman

title:  CSCI 2200 | ALgorithms 

email: ltoma@bowdoin.edu

description: >- # this means to ignore newlines until "baseurl:"
  bla bla bla 

github_username:  lauratoma

plugins:
  - jekyll-feed

